# Copyright (c) 2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

ERRORCONDITIONS = [
    "GENERIC",
    "UNLOCK_REQUIRED",
    "RPC_NOT_FOUND",
    "MSG_DECODE_FAILED",
    "MSG_ENCODE_FAILED",
]

LOCKSTATE = ["LOCKED", "UNLOCKED"]

SAVECHANGESERRORCODE = ["OK", "GENERIC", "NOT_SUPPORTED", "NO_SPACE"]
SETLAYERBINDINGRESPONSE = [
    "OK",
    "INVALID_LOCATION",
    "INVALID_BEHAVIOR",
    "INVALID_PARAMETERS",
]
MOVELAYERERRORCODE = ["OK", "GENERIC", "INVALID_LAYER", "INVALID_DESTINATION"]
ADDLAYERERRORCODE = ["OK", "GENERIC", "NO_SPACE"]
REMOVELAYERERRORCODE = ["OK", "GENERIC", "INVALID_INDEX"]
RESTORELAYERERRORCODE = ["OK", "GENERIC", "INVALID_ID", "INVALID_INDEX"]
SETLAYERPROPSRESPONSE = ["OK", "GENERIC", "INVALID_ID"]
SETACTIVEPHYSICALLAYOUTERRORCODE = ["OK", "GENERIC", "INVALID_LAYOUT_INDEX"]
