# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altar_ii.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'altar_ii.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61ltar_ii.proto\x12\x0czmk.altar_ii\"}\n\x07Request\x12\x17\n\rals_get_state\x18\x01 \x01(\x08H\x00\x12/\n\rals_set_state\x18\x02 \x01(\x0e\x32\x16.zmk.altar_ii.ALSStateH\x00\x12\x18\n\x0eplay_indicator\x18\x03 \x01(\rH\x00\x42\x0e\n\x0crequest_type\"\x7f\n\x08Response\x12/\n\rals_get_state\x18\x01 \x01(\x0e\x32\x16.zmk.altar_ii.ALSStateH\x00\x12\x17\n\rals_set_state\x18\x02 \x01(\x08H\x00\x12\x18\n\x0eplay_indicator\x18\x03 \x01(\x08H\x00\x42\x0f\n\rresponse_type*W\n\x08\x41LSState\x12\x17\n\x13\x41LTAR_II_ALS_ACTIVE\x10\x00\x12\x17\n\x13\x41LTAR_II_ALS_PAUSED\x10\x01\x12\x19\n\x15\x41LTAR_II_ALS_DISABLED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altar_ii_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALSSTATE']._serialized_start=288
  _globals['_ALSSTATE']._serialized_end=375
  _globals['_REQUEST']._serialized_start=32
  _globals['_REQUEST']._serialized_end=157
  _globals['_RESPONSE']._serialized_start=159
  _globals['_RESPONSE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
