# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x08zmk.core\"\xcc\x01\n\x07Request\x12\x19\n\x0fget_device_info\x18\x01 \x01(\x08H\x00\x12\x18\n\x0eget_lock_state\x18\x02 \x01(\x08H\x00\x12\x0e\n\x04lock\x18\x03 \x01(\x08H\x00\x12\x18\n\x0ereset_settings\x18\x04 \x01(\x08H\x00\x12\x1f\n\x15\x63heck_unsaved_changes\x18\x05 \x01(\x08H\x00\x12\x16\n\x0csave_changes\x18\x06 \x01(\x08H\x00\x12\x19\n\x0f\x64iscard_changes\x18\x07 \x01(\x08H\x00\x42\x0e\n\x0crequest_type\"\x93\x02\n\x08Response\x12:\n\x0fget_device_info\x18\x01 \x01(\x0b\x32\x1f.zmk.core.GetDeviceInfoResponseH\x00\x12-\n\x0eget_lock_state\x18\x02 \x01(\x0e\x32\x13.zmk.core.LockStateH\x00\x12\x18\n\x0ereset_settings\x18\x04 \x01(\x08H\x00\x12\x1f\n\x15\x63heck_unsaved_changes\x18\x05 \x01(\x08H\x00\x12\x35\n\x0csave_changes\x18\x06 \x01(\x0b\x32\x1d.zmk.core.SaveChangesResponseH\x00\x12\x19\n\x0f\x64iscard_changes\x18\x07 \x01(\x08H\x00\x42\x0f\n\rresponse_type\"<\n\x15GetDeviceInfoResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x01(\x0c\"V\n\x0cNotification\x12\x31\n\x12lock_state_changed\x18\x01 \x01(\x0e\x32\x13.zmk.core.LockStateH\x00\x42\x13\n\x11notification_type\"\\\n\x13SaveChangesResponse\x12\x0c\n\x02ok\x18\x01 \x01(\x08H\x00\x12-\n\x03\x65rr\x18\x02 \x01(\x0e\x32\x1e.zmk.core.SaveChangesErrorCodeH\x00\x42\x08\n\x06result*[\n\tLockState\x12%\n!ZMK_STUDIO_CORE_LOCK_STATE_LOCKED\x10\x00\x12\'\n#ZMK_STUDIO_CORE_LOCK_STATE_UNLOCKED\x10\x01*\x90\x01\n\x14SaveChangesErrorCode\x12\x17\n\x13SAVE_CHANGES_ERR_OK\x10\x00\x12\x1c\n\x18SAVE_CHANGES_ERR_GENERIC\x10\x01\x12\"\n\x1eSAVE_CHANGES_ERR_NOT_SUPPORTED\x10\x02\x12\x1d\n\x19SAVE_CHANGES_ERR_NO_SPACE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCKSTATE']._serialized_start=753
  _globals['_LOCKSTATE']._serialized_end=844
  _globals['_SAVECHANGESERRORCODE']._serialized_start=847
  _globals['_SAVECHANGESERRORCODE']._serialized_end=991
  _globals['_REQUEST']._serialized_start=25
  _globals['_REQUEST']._serialized_end=229
  _globals['_RESPONSE']._serialized_start=232
  _globals['_RESPONSE']._serialized_end=507
  _globals['_GETDEVICEINFORESPONSE']._serialized_start=509
  _globals['_GETDEVICEINFORESPONSE']._serialized_end=569
  _globals['_NOTIFICATION']._serialized_start=571
  _globals['_NOTIFICATION']._serialized_end=657
  _globals['_SAVECHANGESRESPONSE']._serialized_start=659
  _globals['_SAVECHANGESRESPONSE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
