# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: haptics.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'haptics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhaptics.proto\x12\x0bzmk.haptics\"\xc3\x01\n\x07Request\x12\x14\n\nhaptics_on\x18\x01 \x01(\x08H\x00\x12\x15\n\x0bhaptics_off\x18\x02 \x01(\x08H\x00\x12\x18\n\x0ehaptics_toggle\x18\x03 \x01(\x08H\x00\x12\x17\n\rhaptics_is_on\x18\x04 \x01(\x08H\x00\x12#\n\x19haptics_get_rated_voltage\x18\x05 \x01(\x08H\x00\x12#\n\x19haptics_set_rated_voltage\x18\x06 \x01(\rH\x00\x42\x0e\n\x0crequest_type\"\xc5\x01\n\x08Response\x12\x14\n\nhaptics_on\x18\x01 \x01(\x08H\x00\x12\x15\n\x0bhaptics_off\x18\x02 \x01(\x08H\x00\x12\x18\n\x0ehaptics_toggle\x18\x03 \x01(\x08H\x00\x12\x17\n\rhaptics_is_on\x18\x04 \x01(\x08H\x00\x12#\n\x19haptics_get_rated_voltage\x18\x05 \x01(\rH\x00\x12#\n\x19haptics_set_rated_voltage\x18\x06 \x01(\x08H\x00\x42\x0f\n\rresponse_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'haptics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=31
  _globals['_REQUEST']._serialized_end=226
  _globals['_RESPONSE']._serialized_start=229
  _globals['_RESPONSE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
