# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensors.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'sensors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsensors.proto\x12\x0bzmk.sensors\"]\n\x07Request\x12\x42\n\x12get_sensor_binding\x18\x01 \x01(\x0b\x32$.zmk.sensors.GetSensorBindingRequestH\x00\x42\x0e\n\x0crequest_type\"U\n\x08Response\x12\x38\n\x12get_sensor_binding\x18\x01 \x01(\x0b\x32\x1a.zmk.sensors.SensorBindingH\x00\x42\x0f\n\rresponse_type\"A\n\x17GetSensorBindingRequest\x12\x10\n\x08layer_id\x18\x01 \x01(\r\x12\x14\n\x0csensor_index\x18\x02 \x01(\x05\"D\n\rSensorBinding\x12\x13\n\x0b\x62\x65havior_id\x18\x01 \x01(\x11\x12\x0e\n\x06param1\x18\x02 \x01(\r\x12\x0e\n\x06param2\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=30
  _globals['_REQUEST']._serialized_end=123
  _globals['_RESPONSE']._serialized_start=125
  _globals['_RESPONSE']._serialized_end=210
  _globals['_GETSENSORBINDINGREQUEST']._serialized_start=212
  _globals['_GETSENSORBINDINGREQUEST']._serialized_end=277
  _globals['_SENSORBINDING']._serialized_start=279
  _globals['_SENSORBINDING']._serialized_end=347
# @@protoc_insertion_point(module_scope)
