# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: studio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'studio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import meta_pb2 as meta__pb2
from . import core_pb2 as core__pb2
from . import behaviors_pb2 as behaviors__pb2
from . import keymap_pb2 as keymap__pb2
from . import combos_pb2 as combos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstudio.proto\x12\nzmk.studio\x1a\nmeta.proto\x1a\ncore.proto\x1a\x0f\x62\x65haviors.proto\x1a\x0ckeymap.proto\x1a\x0c\x63ombos.proto\"\xc8\x01\n\x07Request\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12!\n\x04\x63ore\x18\x03 \x01(\x0b\x32\x11.zmk.core.RequestH\x00\x12+\n\tbehaviors\x18\x04 \x01(\x0b\x32\x16.zmk.behaviors.RequestH\x00\x12%\n\x06keymap\x18\x05 \x01(\x0b\x32\x13.zmk.keymap.RequestH\x00\x12%\n\x06\x63ombos\x18\x06 \x01(\x0b\x32\x13.zmk.combos.RequestH\x00\x42\x0b\n\tsubsystem\"}\n\x08Response\x12\x37\n\x10request_response\x18\x01 \x01(\x0b\x32\x1b.zmk.studio.RequestResponseH\x00\x12\x30\n\x0cnotification\x18\x02 \x01(\x0b\x32\x18.zmk.studio.NotificationH\x00\x42\x06\n\x04type\"\xf8\x01\n\x0fRequestResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\"\n\x04meta\x18\x02 \x01(\x0b\x32\x12.zmk.meta.ResponseH\x00\x12\"\n\x04\x63ore\x18\x03 \x01(\x0b\x32\x12.zmk.core.ResponseH\x00\x12,\n\tbehaviors\x18\x04 \x01(\x0b\x32\x17.zmk.behaviors.ResponseH\x00\x12&\n\x06keymap\x18\x05 \x01(\x0b\x32\x14.zmk.keymap.ResponseH\x00\x12&\n\x06\x63ombos\x18\x06 \x01(\x0b\x32\x14.zmk.combos.ResponseH\x00\x42\x0b\n\tsubsystem\"\x9b\x01\n\x0cNotification\x12&\n\x04\x63ore\x18\x02 \x01(\x0b\x32\x16.zmk.core.NotificationH\x00\x12*\n\x06keymap\x18\x05 \x01(\x0b\x32\x18.zmk.keymap.NotificationH\x00\x12*\n\x06\x63ombos\x18\x06 \x01(\x0b\x32\x18.zmk.combos.NotificationH\x00\x42\x0b\n\tsubsystemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'studio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=98
  _globals['_REQUEST']._serialized_end=298
  _globals['_RESPONSE']._serialized_start=300
  _globals['_RESPONSE']._serialized_end=425
  _globals['_REQUESTRESPONSE']._serialized_start=428
  _globals['_REQUESTRESPONSE']._serialized_end=676
  _globals['_NOTIFICATION']._serialized_start=679
  _globals['_NOTIFICATION']._serialized_end=834
# @@protoc_insertion_point(module_scope)
