ERR_SAVE_CHANGES = ["OK", "GENERIC", "NOT_SUPPORTED", "NO_SPACE"]
RESP_SET_LAYER_BINDING = [
    "OK",
    "INVALID_LOCATION",
    "INVALID_BEHAVIOR",
    "INVALID_PARAMETERS",
]
ERR_MOVE_LAYER = ["OK", "GENERIC", "INVALID_LAYER", "INVALID_DESTINATION"]
ERR_ADD_LAYER = ["OK", "GENERIC", "NO_SPACE"]
ERR_REMOVE_LAYER = ["OK", "GENERIC", "INVALID_INDEX"]
ERR_RESTORE_LAYER = ["OK", "GENERIC", "INVALID_ID", "INVALID_INDEX"]
RESP_SET_LAYER_PROPS = ["OK", "GENERIC", "INVALID_ID"]
ERR_SET_ACTIVE_PHYSICAL_LAYOUT = ["OK", "GENERIC", "INVALID_LAYOUT_INDEX"]
